# Change these first
owner: martymarty004 # Your GitHub organization or username, where this repository lives
repo: ha-upptime # The name of this repository

sites:
  - name: Home Assistant
    url: $HAURL
    method: POST
    maxResponseTime: 60000
    
  - name: Fritz Pet
    url: $FRITZ_PET
    type: globalping
    check: "tcp-ping"
    location: italy

  - name: La Casa Blu
    url: $LA_CASA_BLU
    type: globalping
    check: "tcp-ping"
    location: italy

  - name: Chuwi-01
    url: {{ secrets.CHUWI01_URL }}
    check: http
    method: GET
    headers:
      - "CF-Access-Client-Id: ${{ secrets.CF_LCB_ACCESS_CLIENT_ID }}"
      - "CF-Access-Client-Secret: ${{ secrets.CF_LCB_ACCESS_CLIENT_SECRET }}"
      - "Authorization: PVEAPIToken=${{ secrets.PVE_TOKEN_ID }}=${{ secrets.PVE_TOKEN_SECRET }}"
    expectedStatusCodes: [200]
    __dangerous__body_down_if_text_missing: '"node":"chuwi-01","status":"online"'

  - name: Chuwi-02
    url: {{ secrets.CHUWI02_URL }}
    check: http
    method: GET
    headers:
      - "CF-Access-Client-Id: ${{ secrets.CF_LCB_ACCESS_CLIENT_ID }}"
      - "CF-Access-Client-Secret: ${{ secrets.CF_LCB_ACCESS_CLIENT_SECRET }}"
      - "Authorization: PVEAPIToken=${{ secrets.PVE_TOKEN_ID }}=${{ secrets.PVE_TOKEN_SECRET }}"
    expectedStatusCodes: [200]
    __dangerous__body_down_if_text_missing: '"node":"chuwi-02","status":"online"'
    
  - name: ZTE Iulian
    url: $ETERNIUMH
    type: globalping
    check: "tcp-ping"
    location: italy

  - name: EterniumH
    url: {{ secrets.TRUENAS_ETERNIUMH_URL }}
    check: http
    headers:
      - "CF-Access-Client-Id: ${{ secrets.CF_ETERNIUMH_ACCESS_CLIENT_ID }}"
      - "CF-Access-Client-Secret: ${{ secrets.CF_ETERNIUMH_ACCESS_CLIENT_SECRET }}"
      - "Authorization: Bearer ${{ secrets.TRUENAS_ETERNIUMH_API_TOKEN }}"
    expectedStatusCodes: [200]
    
  - name: Fritz PF
    url: $FRITZ_PF
    type: globalping
    check: "tcp-ping"
    location: italy
    
  - name: Piccola Fata
    url: https://www.piccolafata.it/wp-json/
    method: HEAD
    maxResponseTime: 60000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ha-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
